[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# API Routes - redireciona /sistema-disciplinar/api/* para a função serverless
[[redirects]]
  from = "/sistema-disciplinar/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback para sistema-disciplinar
[[redirects]]
  from = "/sistema-disciplinar/*"
  to = "/sistema-disciplinar/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets
[[headers]]
  for = "/sistema-disciplinar/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"