version: '3.8'

services:
  # N8N Automation Platform
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_academia
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=academia2024
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_ENCRYPTION_KEY=academia_encryption_key_2024
      # Full Force Academia Variables
      - ACADEMIA_NAME=Full Force Academia
      - ACADEMIA_LOCATION=Matupá-MT
      - EX_STUDENTS_COUNT=561
      - MONTHLY_POTENTIAL=84150
      - EVOLUTION_API_URL=http://evolution:8080
      - RATE_LIMIT_MESSAGES=20
      - DELAY_BETWEEN_MESSAGES=3000
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    depends_on:
      - postgres
      - redis
    networks:
      - academia_network

  # PostgreSQL Database for N8N
  postgres:
    image: postgres:13
    container_name: postgres_n8n
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - academia_network

  # Evolution API for WhatsApp
  evolution:
    image: davidsongomes/evolution-api:latest
    container_name: evolution_api
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=postgresql://n8n:n8n_password@postgres:5432/n8n
      - REDIS_ENABLED=true
      - REDIS_URI=redis://redis:6379
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379
      - WEBHOOK_GLOBAL_URL=http://n8n:5678/webhook/whatsapp
      - WEBHOOK_GLOBAL_ENABLED=true
      - QRCODE_LIMIT=30
      - AUTHENTICATION_API_KEY=academia_evolution_2024
      - LOG_LEVEL=info
      - DEL_INSTANCE=false
    ports:
      - "8080:8080"
    volumes:
      - evolution_data:/evolution/instances
    depends_on:
      - postgres
      - redis
    networks:
      - academia_network

  # Redis for Queue Management
  redis:
    image: redis:7-alpine
    container_name: redis_academia
    restart: unless-stopped
    command: redis-server --requirepass academia_redis_2024
    volumes:
      - redis_data:/data
    networks:
      - academia_network

  # Adminer for Database Management
  adminer:
    image: adminer:latest
    container_name: adminer_academia
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - academia_network

volumes:
  n8n_data:
  postgres_data:
  evolution_data:
  redis_data:

networks:
  academia_network:
    driver: bridge