version: '3.8'

services:
  # N8N Automation Platform
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-mcp
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - N8N_BASIC_AUTH_ACTIVE=false
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_ENCRYPTION_KEY=academia_encryption_key_2024
      # Full Force Academia Variables
      - ACADEMIA_NAME=Full Force Academia
      - ACADEMIA_LOCATION=Matupá-MT
      - EX_STUDENTS_COUNT=561
      - MONTHLY_POTENTIAL=84150
      - EVOLUTION_API_URL=http://evolution:8080
      - RATE_LIMIT_MESSAGES=20
      - DELAY_BETWEEN_MESSAGES=3000
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    depends_on:
      - postgres
      - redis
    networks:
      - academia_network

  # PostgreSQL Database for N8N
  postgres:
    image: postgres:13
    container_name: postgres_n8n
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - academia_network

  # Evolution API placeholder - to be configured later
  # evolution:
  #   image: evolutionapi/evolution-api:latest
  #   container_name: evolution_api

  # Redis for Queue Management
  redis:
    image: redis:7-alpine
    container_name: redis_academia
    restart: unless-stopped
    command: redis-server --requirepass academia_redis_2024
    volumes:
      - redis_data:/data
    networks:
      - academia_network

  # Adminer for Database Management
  adminer:
    image: adminer:latest
    container_name: adminer_academia
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - academia_network

volumes:
  n8n_data:
  postgres_data:
  evolution_data:
  redis_data:

networks:
  academia_network:
    driver: bridge